server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
logging:
  level:
    com.nbclass: DEBUG
    tk.mybatis: DEBUG
    org.springframework: WARN
#  file: log/zb-shiro.log
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.159.24.181:3306/paper?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: hello #root
    password: Password123_ #123456
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    filters: stat,wall,slf4j
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 600MB

mybatis:
  type-aliases-package: com.nbclass.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.nbclass.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

file-info:
  file-dir: /Users/huangkexiang/0ProjectFileDir
  tem-dir: /Users/huangkexiang/01ProjectFileTemDir
  icon-map: {doc: fa-file-word-o,xls: fa-file-excel-o,ppt: fa-file-powerpoint-o,
             zip: fa-file-zip-o,rar:  fa-file-zip-o,7z: fa-file-zip-o,txt: fa-file-text-o,
             pdf: fa-file-pdf-o,video: fa-file-movie-o,image: fa-file-image-o,
             js:  fa-code, java: fa-code, py: fa-code, htm: fa-chrome}
